#ifndef __BOONDOCK_GPIO__
#define __BOONDOCK_GPIO__

// SD Card

//#define PIN_AUDIO_KIT_SD_CARD_CS GPIO_NUM_13
//#define PIN_AUDIO_KIT_SD_CARD_MISO GPIO_NUM_2
//#define PIN_AUDIO_KIT_SD_CARD_MOSI GPIO_NUM_15
//#define PIN_AUDIO_KIT_SD_CARD_CLK GPIO_NUM_14

#define GPIO_KEY_PTT GPIO_NUM_36
#define GPIO_KEY_PREV GPIO_NUM_23
#define GPIO_KEY_NEXT GPIO_NUM_19
#define GPIO_KEY_VOL GPIO_NUM_5
#define GPIO_KEY_MODE GPIO_NUM_0


#define NEOPIXEL_PIN GPIO_NUM_22 // Pin for Neopixel

#endif